import { generateReleaseNotes } from "@/lib/release/release-notes-generator";
import {
  RELEASE_ARTIFACT_ROOT,
  RELEASE_FACTORY_VERSION,
  type GithubPublishReport,
  type ReleaseBundle,
  type ReleaseManifest,
  type ReleasePresentationFields,
  type ReleaseReport,
  type RepositoryManifest,
} from "@/lib/release/types";

export const RELEASE_PATHS = {
  root: RELEASE_ARTIFACT_ROOT,
  bundle: `${RELEASE_ARTIFACT_ROOT}/bundle/project_bundle.zip`,
  releaseManifest: `${RELEASE_ARTIFACT_ROOT}/release_manifest.json`,
  releaseReport: `${RELEASE_ARTIFACT_ROOT}/release_report.json`,
  releaseNotes: `${RELEASE_ARTIFACT_ROOT}/github/release_notes.md`,
  repositoryManifest: `${RELEASE_ARTIFACT_ROOT}/github/repository_manifest.json`,
  githubReport: `${RELEASE_ARTIFACT_ROOT}/github/github_publish_report.json`,
} as const;

export interface ArtifactAvailability {
  readme: boolean;
  demo_video: boolean;
  screenshots: boolean;
  project_card: boolean;
  package_artifacts: boolean;
}

export function generateReleaseManifest(
  projectName: string,
  availability: ArtifactAvailability
): ReleaseManifest {
  const bundleReady =
    availability.readme &&
    availability.project_card &&
    availability.package_artifacts;

  return {
    project_name: projectName,
    version: RELEASE_FACTORY_VERSION,
    readme: availability.readme,
    demo_video: availability.demo_video,
    screenshots: availability.screenshots,
    project_card: availability.project_card,
    package_artifacts: availability.package_artifacts,
    bundle_ready: bundleReady,
  };
}

export function generateRepositoryManifest(projectName: string): RepositoryManifest {
  const slug = projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

  return {
    repository_name: slug || "saas-idea-mvp-factory-web",
    repository_description: `Self-presenting MVP generated by SAAS_IDEA_AI_MVP_FACTORY — ${projectName}`,
    topics: ["mvp", "saas", "ai-factory", "self-presenting", "nextjs"],
    default_branch: "main",
    license: "MIT",
  };
}

export function generateGithubPublishReport(bundleReady: boolean): GithubPublishReport {
  return {
    github_ready: bundleReady,
    release_ready: bundleReady,
    bundle_ready: bundleReady,
  };
}

export function generateReleaseReport(
  bundleReady: boolean,
  filesIncluded: string[]
): ReleaseReport {
  return {
    bundle_ready: bundleReady,
    zip_path: RELEASE_PATHS.bundle,
    files_included: filesIncluded,
    generated_at: new Date().toISOString(),
    factory_version: RELEASE_FACTORY_VERSION,
  };
}

export function generatePresentationReleaseFields(bundleReady: boolean): ReleasePresentationFields {
  return {
    release_ready: bundleReady,
    bundle_path: RELEASE_PATHS.bundle,
    release_manifest: RELEASE_PATHS.releaseManifest,
    release_notes: RELEASE_PATHS.releaseNotes,
  };
}

export function generateReleaseBundle(
  projectName: string,
  availability: ArtifactAvailability,
  t: (key: string) => string,
  filesIncluded: string[] = []
): ReleaseBundle {
  const releaseManifest = generateReleaseManifest(projectName, availability);
  const bundleReady = releaseManifest.bundle_ready;
  const repositoryManifest = generateRepositoryManifest(projectName);
  const githubPublishReport = generateGithubPublishReport(bundleReady);
  const releaseNotes = generateReleaseNotes(projectName, releaseManifest, t);
  const releaseReport = generateReleaseReport(bundleReady, filesIncluded);
  const presentationFields = generatePresentationReleaseFields(bundleReady);

  return {
    releaseManifest,
    releaseReport,
    repositoryManifest,
    githubPublishReport,
    releaseNotes,
    presentationFields,
  };
}
